<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script>
            var url = "id" ;
            var value = "" ;
            $(document).ready( function () {
                $("#selectcid").change(function () {
                    $(this).val() ;
                    value = $(this).val() ;
                    window.location.href = '?' + url + '=' + value + '&' ;
                })
            }) ;
        </script>
    </head>
    <style>

    </style>
    <body >
    <div class="row justify-content-center">
        <div class="col-10" style="top:-30px;">
            <div id="carouselhome" class="carousel slide " data-rride="carousel" style="background-color:black">
                <ol class="carousel-indicators">
                    <li data-target="carouselhome" data-slide-to="0" class="active"></li>
                    <li data-target="carouselhome" data-slide-to="1"></li>
                    <li data-target="carouselhome" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" style="background-color:black">
                    <div class="carousel-item active" style="background-color:black">
                        <img class="d-block w-100" src="img/a.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="img/b.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="img/c.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselhome" role="button" data-slide="prev" style="background-color:black">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselhome" role="button" data-slide="next" style="background-color:black">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    
    <div class="row" style="padding:30px 20px">
        <div class="col-md-3" style="padding:0px">
            <a href="" style="text-decoration:none;color:black" alt="Plan">
                <div class="card" style="box-shadow: 0 4px 4px 0 rgba(0,0,0,0.1);">
                    <div class="card-body" style="text-align:center">
                        <span class="fa fa-child fa-3x"> </span><br>
                        <div style="padding:10px">Start Career</div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-3" style="padding:0px">
            <a href="" style="text-decoration:none;color:black" alt="Securing My Family">
                <div class="card" style="box-shadow: 0 4px 4px 0 rgba(0,0,0,0.1);">
                    <div class="card-body" style="text-align:center">
                        <span class="fa fa-home fa-3x"> </span><br>
                        <div style="padding:10px">Securing My Family</div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-3" style="padding:0px">
            <a href="" style="text-decoration:none;color:black">
                <div class="card" style="box-shadow: 0 4px 4px 0 rgba(0,0,0,0.1);">
                    <div class="card-body" style="text-align:center" alt="Planning for the Future">
                        <span class="fa fa-book fa-3x"> </span><br>
                        <div style="padding:10px">Planning for the Future</div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-3" style="padding:0px">
            <a href="" style="text-decoration:none;color:black">
                <div class="card" style="box-shadow: 0 4px 4px 0 rgba(0,0,0,0.1);">
                    <div class="card-body" style="text-align:center" alt="Preparing for Retirement">
                        <span class="fa fa-coffee fa-3x"> </span><br>
                        <div style="padding:10px">Preparing for Retirement</div>
                    </div>
                </div>
            </a>
        </div>
    </div>

    
    <div>
        <!-- <h3>Trade</h3>
        <table class="table table-striped table-bordered table-dark" >
            <thead>
                <tr>
                    <th scope="col">Money</th>
                    <th scope="col">BUY</th>
                    <th scope="col">SALE</th>
                </tr>
            </thead>
            <tbody style="">
                <tr>
                   <th scope="row">USA</th>
                   <td>0.3</td>
                   <td>0.33</td> 
                </tr>
                <tr>
                    <th scope="row">JPY</th>
                    <td>3.0</td>
                    <td>3.3</td>
                </tr>
            </tbody>

        </table> -->
        
    </div>

    <!-- <p>You're now flying with Phalcon. Great things are about to happen!</p>

    <p>This page is located at <code>views/index/index.phtml</code></p>
    <a href="<?php echo $this->url->getBaseUri().'index/aaa'?>">dasd</a>
    <div class="page-header">
        <h1>Congratulations!</h1>
    </div>

    <div class="container">
        fjlsdgfhsdklgewash;rfejkl
    </div> -->

        <!-- // if( $this->cookies->has('id') ){
            // $q = $this->cookies->get('id') ;
        // }
        // var_dump($q) ;
        // exit() ;
     -->
    </body>
</html>