<html>
    <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script>
            var url = "id" ;
            var value = "" ;
            $(document).ready( function () {
                $("#selectcid").change(function () {
                    $(this).val() ;
                    value = $(this).val() ;
                    window.location.href = '?' + url + '=' + value + '&' ;
                })
            }) ;
        </script>

    </head>
    <body style="background-color:#222;color:white">
        <div class="row" style="padding:30px 0px">
            <div class="col-6">
                <h2>Calendar</h2>
            </div>
            <div class="col-6" style="text-align:end">
                <?php echo $this->tag->linkTo('officer/createcalendar?id=','<button class="btn btn-primary"><h5>Create</h5></button>')?>
            </div>
        </div>
            <?php for ( $i = 0 ; $i < count($cid) ; $i++ ){ ?>
                <div class="card" style="color:black;padding:30px 0px">
                    <div class="row">
                        <div class="col-3" style="text-align:center;padding:20px">
                            <span class="fas fa-user-circle fa-10x" style="height:100%"></span>
                        </div>
                        <div class="col-6" style="padding:20px">
                            <h5>
                                <div class="row" style="padding:10px 10px 0px">
                                    <div class="col-3" style="text-align:end">
                                        Name :
                                    </div>
                                    <div class="col-6" style="">
                                        <?php echo "$fname[$i] $sname[$i]" ?>
                                    </div>
                                </div>
                                <div class="row" style="padding:10px 10px 0px">
                                    <div class="col-3" style="text-align:end">
                                        Phone :
                                    </div>
                                    <div class="col-6">
                                        <?php echo $phone[$i] ?>
                                    </div>
                                </div>
                                <div class="row" style="padding:10px 10px 0px">
                                    <div class="col-3" style="text-align:end">
                                        Address :
                                    </div>
                                    <div class="col-6">
                                        <?php echo $address[$i] ?>
                                    </div>
                                </div>
                                <div class="row" style="padding:10px 10px 0px">
                                    <div class="col-3" style="text-align:end">
                                        Work :
                                    </div>
                                    <div class="col-6">
                                        <?php echo $work[$i] ?>
                                    </div>
                                </div>
                            </h5>
                        </div>
                        <div class="col-3" style="padding:30px 80px;text-align:end">
                            <h5>
                                <div class="row" style="padding:0px 0px 10px"> 
                                    Date:
                                </div>
                                <div class="row">
                                    <?php echo $calendar[$i] ?>
                                </div>
                            </h5>
                        </div>
                    </div>
                </div>
                <div style="padding-top:30px">
                    
                </div>
            <?php } ?>
    </body>
</html> 