<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script>
            var url = "id";
            var value = "";
            $(document).ready(function() {
                $("#selectcid").change(function(){
                    $(this).val() ;
                    value = $(this).val();
                    window.location.href = '?' + url + '=' + value + '&' ;
                });
            });

            
        </script>
        <script>
            $(document).ready(function()){
                $("#selectcredit").change(function(){
                    $(this).val() ;
                    value1 = $(this).val();
                    window.location.href = '?' + url + '=' + value1 + '&' ;
                })
            });
        </script>
        <script>
            function cal() {
                var n = parseInt(document.getElementById("addsub").value) ;
                var op = document.getElementById("sel").value ;

                if ( op === '+' ){
                    document.getElementById("addsub1") = n*1 ; 
                }else if ( op === '-' ){
                    document.getElementById("addsub1") = n*(-1) ;
                }
            }
        </script>
    </head>
    <body style="background-color:#222;color:white">
    <div class="row" style="padding:30px"><h1>Customer</h1></div>
    <div class="col-12" style="padding:20px 30px 0px">
        <!-- <form method="post"> -->
                <div class="row">
                    <div class="col-10 mr-auto form-group">
                        <select class="form-control" id="selectcid" >
                            <option selected disabled>Select Customer</option>
                            <?php for ($i = 0 ; $i < count($cid) ; $i++ ) { ?>
                                <option value="<?php echo $cid[$i] ?>"><?php echo $cid[$i] ?> </option>
                            <?php } ?>
                        </select>
                    </div>
                    
                </div>
        <!-- </form> -->
        
    </div>
    
    <?php if ( $_GET['id'] != null ) { ?>
        <div style="padding:10px 30px 30px;">
            <div class="card" style="color:black">
                <div class="card-header">
                    <h4>History (#<?php echo$id?>)</h4>
                </div>
                <div class="card-body">
                    <form method="post">
                    <h5>
                        <div class="row">
                            <div class="col-4">
                                <div  class="row">
                                    <div class="col-6" style="text-align:end">
                                        ID : 
                                    </div>
                                    <div class="col-6">
                                        <input type="text" class="form-control" id="id" value="<?php echo $id ?>" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="row">
                                    <div class="col-6" style="text-align:end">
                                        Name :
                                    </div>
                                    <div class="col-6">
                                        <input type="text" class="form-control" name="name" value="<?php echo $fname ?>" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="row">
                                    <div class="col-6" style="text-align:end">
                                        Surname : 
                                    </div>
                                    <div class="col-6">
                                        <input type="text" class="form-control" name="surname" value="<?php echo $sname ?>" required>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="padding:30px 0px 0px">
                            <div class="col-4">
                                <div class="row">
                                    <div class="col-6" style="text-align:end">
                                        BirthDay :
                                    </div>
                                    <div class="col-6">
                                        <input type="text" class="form-control" name="dateof" value="<?php echo $dob ?>" required>
                                        
                                    </div>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="row">
                                    <div class="col-6" style="text-align:end">
                                        Email : 
                                    </div>
                                    <div class="col-6">
                                        <input type="text" class="form-control" name="mail" value="<?php echo $email ?>" required>
                                        
                                    </div>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="row">
                                    <div class="col-6" style="text-align:end">
                                        Phone : 
                                    </div>
                                    <div class="col-6">
                                        <input type="text" class="form-control" name="phone" value="<?php echo $pnum ?>" required>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="padding:30px 0px 0px">
                            <div class="col-6">
                                <div class="row">
                                    <div class="col-4" style="text-align:end">
                                        Home : 
                                    </div>
                                    <div class="col-8">
                                        <input type="text" class="form-control" name="home" value="<?php echo $address ?>" required>
                                        
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="row">
                                    <div class="col-4" style="text-align:end">
                                        Work : 
                                    </div>
                                    <div class="col-8">
                                        <input type="text" class="form-control" name="workat" value="<?php echo $work ?>" required>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="padding:30px 0px 0px">
                            <div class="col-2" style="text-align:end">
                                Balance :
                            </div> 
                            <div class="col-3">
                                <input type="text" class="form-control" name="balancea" value="<?php echo $balance ?>" disabled>
                            </div>
                            <div class="col-2" style="text-align:end">
                                Add/Sub :
                            </div>
                            <!-- <div class="col-2">
                                <select class="form-control" id="sel">
                                    <option disabled selected>Selected</option>
                                    <option value="+">Add</option>
                                    <option value="-">Sub</option>
                                </select>
                            </div>
                            <div class="col-3">
                                <input type="text" name="addsub" class="form-control">
                            </div> -->
                            <div class="col-4">
                                <input type="text" name="addsub1" class="form-control">
                            </div>
                        </div>
                        <div class="row justify-content-center" style="padding:40px 20px 5px">
                            <button type="submit" class="btn btn-primary" style="padding:10px 10px" onclick="cal();">Submit</button>
                        </div>
                    </h5>
                    </form>
                </div>
            </div>
        </div>
    <?php } else { ?>
        <div style="padding:10px 30px 30px">
            <div class="card" style="color:black">
                <div class="card-header">
                    <h4>History (#)</h4>
                </div>
                <div class="card-body">
                    <h5>
                        <div class="row">
                            <div class="col-4">
                                ID : 
                            </div>
                            <div class="col-4">
                                Name : 
                            </div>
                            <div class="col-4">
                                Surname : 
                            </div>
                        </div>
                        <div class="row" style="padding:30px 0px 0px">
                            <div class="col-4">
                                BirthDay : 
                            </div>
                            <div class="col-4">
                                Email : 
                            </div>
                            <div class="col-4">
                                Phone : 
                            </div>
                        </div>
                        <div class="row" style="padding:30px 0px 0px">
                            <div class="col-6">
                                Home : 
                            </div>
                            <div class="col-6">
                                Work :
                            </div>
                        </div>
                    </h5>
                </div>
            </div>
        </div>
    <?php } ?>
    </body>

</html>