<html>
    <head>

    </head>
    <body style="background-color:black ;">
    <div class="container border border-white" style="color:white">
            <div class="col align-items-center" style="padding:50px">
                <div class="row justify-content-center" style="padding:70px">
                    <div class="row"><h1>Logo</h1></div>   

                </div>
                <div class="row justify-content-center" style="padding:30px">
                    <h3>Sign in Officer</h3>
                </div>
                <form method="post">
                    <div class="form-group row" style="padding:10px">
                        <div class="col-10 mx-auto" >
                        <input name="id" type="Username" class="form-control" placeholder="Username" style="padding:20px" required>
                        </div>
                    </div>
                    <div class="form-group row" style="padding:10px">
                        <div class="col-10 mx-auto">
                        <input name="password" type="password" class="form-control" placeholder="Password" style="padding:20px" required>
                        </div>
                    </div>
                    <!-- <div class="col-md-8"> -->
                    <div class="row justify-content-center">
                    <div class="col-md-6">
                        <div class="row justify-content-center">
                            <!-- <h6>Forget your password?</h6> -->
                        </div>
                    </div>
                    <!-- <div class="col-md-auto">
                        <h6>Don't have an account?</h6>
                    </div> -->
                    <div class="col-md-6">
                        <div class="row justify-content-center">
                            <!-- <h6>Sign Up?</h6> -->
                        </div>
                    </div>
                    </div>
                    <div class="from-group row justify-content-center" style="padding:30px">
                        <input type="submit" class="btn btn-primary" value="Sign in" style="padding:10px 20px">
                    </div>
                </form>
                
            </div>
        </div>
    </body>
</html>