<html>
    <head>
    </head>
    <body>
    <form method="post">
        <div class="col-12" style="border-style:solid;padding:50px;background-color:rgb(69,69,69,0.2);">
            <div class="col-1" style="text-align:end">
                ADDED !! :
            </div>
            <div class="row justify-content-center" style="padding:40px 20px 5px">
                <button type="submit" class="btn btn-primary" style="padding:10px 10px">GoBack</button>
            </div>
        </div>
        </form>
    </body>
</html>