<html>
    <head>

    </head>
    <body style="">
        <div style="padding:30px"><h2>Calendar</h2></div>
        
            <div class="card border">
                <div class="col-12" style="padding:20px 50px">
                    <div class="row">
                    <div class="col-4">
                        
                        <h5> date </h5>
                    </div>
                    <div class="col-6">
                        รายละเอียด
                    </div>
                    <div class="col-2">
                        
                        <h5> officers </h5> 
                    </div>
                    </div>


                </div>
            </div>

    </body>
</html>

<!-- <?php for ( $i = 0 ; $i < count($date) ; $i++) {
             ?>
        <?php } ?> -->