<html>
    <head>

    </head>
    <body>
    <form method="post"> 
        <div class="col-12" style="padding:50px;border-style:solid">
            
                <div class="row justify-content-center" >
                    <div class="col-12">
                        <div class="row" >
                            <div class="col-4" style="padding:5px 20px">
                                <div class="row justify-content-end">
                                    <h5>Current :</h5>  
                                </div>
                            </div>
                            <div class="col-6">
                                <input class="form-control" type="password" name="currentpass" required>
                            </div>
                        </div>
                        <div class="row" style="padding:20px 0px">
                            <div class="col-4 align-items-end" style="padding:5px 20px">
                                <div class="row justify-content-end">
                                    <h5>New :</h5>  
                                </div>
                            </div>
                            <div class="col-6" >
                                <input class="form-control" type="password" name="newpass" required>
                            </div>
                        </div>
                        <div class="row" >
                            <div class="col-4">
                                <div class="row justify-content-end">
                                    <h5>Confirm :</h5>  
                                </div>
                            </div>
                            <div class="col-6">
                                <input class="form-control" type="password" name="conpass" required>
                            </div>
                        </div>
                    </form>
                    </div>
                </div>
                <div class="row justify-content-center" style="padding:30px">
                    <input class="btn btn-primary" type="submit" value="Submit">
                </div>
        </div>
        </form>
    </body>
</html>