<html>
    <head>

    </head>
    <body>
        <h2 style="padding:50px 50px 20px"><center> Credit Card </center></h2>
        <div style="padding:30px 250px 250px;">
            <div class="container-fluid" style="color:white">
            <div class="alert alert-primary" style="color:white">
                <?php
                if($Creditcardnumber != 0) {
                for ( $i = 0 ; $i < count($Creditcardnumber) ; $i++){ ?>
                    <div style="text-align:center"><h3 class="alert-heading">Logo</h3></div>
                    <h3>Credit Number : <?php echo $Creditcardnumber[$i] ?> </h5>
                    <h3>expire date : <?php echo $expire_date[$i] ?></h5>
                    <h3>Money : <?php echo $limit[$i] ?></h4>
                    <?php } ?> 
                <?php } ?>    
                </div>
            </div>
            <div class="row justify-content-end" style="padding:5px"><?php echo $this->tag->linkTo('index', '<button class="btn btn-primary"><span class="fas fa-long-arrow-alt-left fa-2x" style="padding:0px 20px"></span></button>') ?></div>
        </div>        
        <!-- <div class="border-bottom" style="padding:20px 0px 20px"></div> -->
        
        
    </body>
</html>