<html>
    <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
        var url = "id" ;
        var value = "" ;
        $(document).ready( function () {
            $("#selectcid").change(function () {
                $(this).val() ;
                value = $(this).val() ;
                window.location.href = '?' + url + '=' + value + '&' ;
            })
        }) ;
    </script>

    </head>
    <body>
       
        <div class="row" style="padding:30px 0px">
            <div class="col-10 mr-auto form-group">
                <select class="form-control" id="selectcid" >
                    <option selected disabled>Select Loan</option>
                    <?php for ($i = 0 ; $i < count($manyloan) ; $i++ ) { ?>
                        <option value="<?php echo $manyloan[$i] ?>"><?php echo $manyloan[$i] ?> </option>
                    <?php } ?>
                </select>
            </div>                  
        </div>
        <?php if ( $_GET['id'] != null ) { ?>
                
                <div class="card" style="color:black">
                    <div class="row">
                        <div class="col-3" style="text-align:center;padding:20px">
                            <span class="fas fa-user-circle fa-10x" style="height:100%"></span>
                        </div>
                        <div class="col-6" style="padding:20px">
                            <h5>
                                <div class="row" style="padding:10px 10px 0px">
                                    <div class="col-4" style="text-align:end">
                                        LoanId :
                                    </div>
                                    <div class="col-8" style="">
                                        <?php echo "$loanidd" ?>
                                    </div>
                                </div>
                                <div class="row" style="padding:10px 10px 0px">
                                    <div class="col-4" style="text-align:end">
                                        LoanAmount :
                                    </div>
                                    <div class="col-8">
                                        <?php echo $loanamount ?>
                                    </div>
                                </div>
                                <div class="row" style="padding:10px 10px 0px">
                                    <div class="col-4" style="text-align:end">
                                        Insterestrate :
                                    </div>
                                    <div class="col-8">
                                        <?php echo $insterestrate ?>
                                    </div>
                                </div>
                                <div class="row" style="padding:10px 10px 0px">
                                    <div class="col-4" style="text-align:end">
                                        Pay_Per_Month 
                                    </div>
                                    <div class="col-8">
                                        <?php echo $pay_per_month ?>
                                    </div>
                                </div>
                            </h5>
                        </div>
                    </div>
                </div>
                <div style="padding-top:30px">
                    <table class="table table-bordered table-light" style="color:black">
                        <thead>
                            <tr class="">
                                <th scope="col">Date</th>
                                <!-- <th scope="col">id</th> -->
                                <th scope="col">Balance</th>
                                <th scope="col">payingid</th>
                                <th scope="col">loanid</th>
                                <!-- <th scope="col">Address</th> -->
                                <!-- <th scope="col">Email</th> -->
                            </tr>
                        </thead>
                        <tbody>
                        
                                <?php
                                    if($cusid != 0){
                                        for ( $i = 0 ; $i < count($cusid) ; $i++ ) { ?>
                                        <tr>
                                            <th scope="row"><?php echo $date[$i] ?></th>
                                            <td><?php echo $bal[$i] ?></td>
                                            <td><?php echo $payid[$i] ?></td>
                                            <td><?php echo $loanid[$i] ?></td>
                                        </tr>
                                        <?php } ?>
                                <?php } ?>
                        </tbody>
                    </table>
                </div>
            <?php } ?>  
    </body>
</html> 