<html>
    <head>

    </head>
    <body>
        <h2 style="padding:50px 50px 20px"> Statement </h2>
        <table class="table table-hover">
            <thead class="thead">
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Time</th>
                    <th scope="col">Debit/Credit</th>
                    <th scope="col">Balance/Baht</th>
                </tr>

            </thead>
            <tbody>
                <?php 
                    if($date != 0) {
                    for ( $i = 0 ; $i < count($date) ; $i++){
                    ?> <tr>
                        <!-- <th scope="row" style="padding:20px"> <?php echo $i ?> </th>  -->
                        <td style="padding:10px"><?php echo $date[$i] ; ?> </td>
                        <td style="padding:10px"><?php echo $i ?></td>
                        <td style="padding:10px"><?php echo $payingid[$i] ; ?> </td>
                        <td style="padding:10px"><?php echo $amount[$i] ?> </td>
                        <!-- <td> </td> -->
                        </tr> 
                        <?php } ?>    
                    <?php } ?>
            </tbody>
        </table>
        <!-- <div class="border-bottom" style="padding:20px 0px 20px"></div> -->
        <div class="row justify-content-end" style="padding:50px"><?php echo $this->tag->linkTo('index', '<button class="btn btn-primary"><span class="fas fa-long-arrow-alt-left fa-2x" style="padding:0px 20px"></span></button>') ?></div>
        
    </body>
</html>