<html>
    <head>

    </head>
    <body>
        <div class="container" style="border-style:solid">
            <div class="col align-items-center" style="padding:50px">
                <div class="row justify-content-center" style="padding:70px">
                    <div class="row"><h1>Logo</h1></div>   

                </div>
                <div class="row justify-content-center" style="padding:30px">
                    <h3>Sign in Bank</h3>
                </div>
                <form method="post">
                    <div class="form-group row" style="padding:10px">
                        <div class="col-10 mx-auto" >
                        <input name="usernamelogin" type="Username" class="form-control" placeholder="Username" style="padding:20px" required>
                        </div>
                    </div>
                    <div class="form-group row" style="padding:10px">
                        <div class="col-10 mx-auto">
                        <input name="passwordlogin" type="password" class="form-control" placeholder="Password" style="padding:20px" required>
                        </div>
                    </div>
                    <!-- <div class="col-md-8"> -->
                    <div class="row justify-content-center">
                    <div class="col-md-6">
                        <div class="row justify-content-center">
                            <h6>Forget your password?</h6>
                        </div>
                    </div>
                    <!-- <div class="col-md-auto">
                        <h6>Don't have an account?</h6>
                    </div> -->
                    <div class="col-md-6">
                        <div class="row justify-content-center">
                        <?php echo $this->tag->linkTo('login/register', "<div style='color:black;padding:10px'><h6>Sign up</h6></div>") ?>
                        </div>
                    </div>
                    </div>
                    <div class="from-group row justify-content-center" style="padding:30px">
                        <input type="submit" class="btn btn-warning" value="Sign in" style="padding:10px 20px">
                    </div>
                    
                </form>
                    <div><?php $this->flashSession->output() ; ?></div>
                
            </div>
        </div>
    </body>

</html>