<html>
    <head>

    </head>
    <body>
        <div class="container" style="border-style:solid">
            <div class="col align-items-center" style="padding:50px">
                <div class="row justify-content-center" style="padding:70px">    
                    <div class="row"><h1>Logo</h1></div>   

                </div>
                <div class="row justify-content-center" style="padding:30px">
                    <h3>Sign Up</h3>
                </div>     
                <form method="post">
                    <div class="form-group row" style="padding:10px">
                        <div class="col-10 mx-auto" >
                        <input name="username" type="Username" class="form-control" placeholder="Username" style="padding:20px" required>
                        </div>
                    </div>
                    <div class="form-group row" style="padding:10px">
                        <div class="col-10 mx-auto" >
                        <input name="password" type="Password" class="form-control" placeholder="Password" style="padding:20px" required>
                        </div>
                    </div>
                    <div class="form-group row" style="padding:10px">
                        <div class="col-10 mx-auto" >
                        <input name="email" type="email" class="form-control" placeholder="Email" style="padding:20px" required>
                        </div>
                    </div>
                    <div class="form-group row" style="padding:10px">
                        <div class="col-10 mx-auto" >
                        <input name="pnumber" type="text" class="form-control" placeholder="Phone Number" style="padding:20px" required>
                        </div>
                    </div>
                    <div class="form-group row" style="padding:10px">
                        <div class="col-10 mx-auto" >
                        <input name="fname" type="text" class="form-control" placeholder="Firstname" style="padding:20px" required>
                        </div>
                    </div>
                    <div class="form-group row" style="padding:10px">
                        <div class="col-10 mx-auto" >
                        <input name="lname" type="text" class="form-control" placeholder="Lastname" style="padding:20px" required>
                        </div>
                    </div>
                    <div class="form-group row" style="padding:10px">
                        <div class="col-10 mx-auto" >
                        <input name="gender" type="text" class="form-control" placeholder="Gender" style="padding:20px" required>
                        </div>
                    </div>
                    <div class="form-group row" style="padding:10px">
                        <div class="col-10 mx-auto" >
                        <input name="dob" type="text" class="form-control" placeholder="Birth Day" style="padding:20px" required>
                        </div>
                    </div>
                    <div class="form-group row" style="padding:10px">
                        <div class="col-10 mx-auto" >
                        <input name="homeadd" type="text" class="form-control" placeholder="Home Address" style="padding:20px" required>
                        </div>
                    </div>
                    <div class="form-group row" style="padding:10px">
                        <div class="col-10 mx-auto" >
                        <input name="workadd" type="text" class="form-control" placeholder="Work Address" style="padding:20px" required>
                        </div>
                    </div>
                    <div class="from-group row justify-content-center" style="padding:30px">
                        <input type="submit" class="btn btn-warning" value="Sign up" style="padding:10px 20px">
                    </div>
                    
                </form>
                <div><?php $this->flashSession->output() ; ?></div>
                </div>  
            </div>
            <div class="row justify-content-end" style="padding:5px"><?php echo $this->tag->linkTo('login', '<button class="btn btn-primary"><span class="fas fa-long-arrow-alt-left fa-2x" style="padding:0px 20px"></span></button>') ?></div>
        </div>
    </body>

</html>